### ISSUE TITLE
can TLS be used on dd-wrt?

### ISSUE THREAD

**Issue by 2SI3NX** [nsupdate-info/nsupdate.info#299] opened 2017-01-31 09:37 UTC
Just noticed that TLS is not used when configuring dd-wrt. Is it possible to enable secure connection?

**Comment by ThomasWaldmann** [comment] 2017-01-31 13:01
@2SI3NX well, just try it.

The server side supports TLS, so if your router (correctly) implements TLS dyndns updates, it should work.

If it works, please provide some feedback how you got it working, so we can update the information shown after adding a host.

**Comment by 2SI3NX** [comment] 2017-01-31 13:20
i did try it, and it registers on nsupdate profile as 'no TLS', i only followed the instructions you put on setting up nsupdate.info on dd-wrt. I dont see any setting to make it connect with TLS, so thats why im asking is there any additional setting or command under "URL" or "Additional DDNS Options" on the latest dd-wrt that you could use to connect with TLS to your servers?

**Comment by ThomasWaldmann** [comment] 2017-01-31 14:00
I can't help you with ddwrt configuration, I don't have a device with it. If you do not see an option on the UI of it, maybe it just does not support TLS ("SSL").  Maybe just ask the ddwrt developers?

**Comment by elnappo** [comment] 2017-01-31 14:07
Note: https://www.dd-wrt.com/wiki/index.php/Dynamic_DNS#Secure_DDNS_Updates_Over_HTTPS.2FSSL

**Comment by 2SI3NX** [comment] 2017-01-31 14:13
seems like inadyn latest version is not officially supported yet on dd-wrt:
http://svn.dd-wrt.com/ticket/3551

@elnappo i saw that link, could work but im hesitant to mess around with it, especially if they are on the verge of updating and supporting inadyn latest version.

**Comment by ThomasWaldmann** [comment] 2017-01-31 14:22
inadyn (in general) supports tls/ssl (since quite a while).

I am not much a fan of replacing (good) dyndns updaters with some more-or-less quickhack scripts and curl/wget (they often do not implement dyndns spec correctly).

**Comment by ThomasWaldmann** [comment] 2017-05-25 20:44
I am closing this.

It seems that the root cause of this issue might be dd-wrt not having a more-or-less current version of inadyn (like: of the last few years) as a package.

I used inadyn myself a while ago (not on ddwrt), it can do TLS.

**Closed by ThomasWaldmann** 2017-05-25 20:44 UTC
